backend:
  name: github
  repo: DeaaMalaika/my-portfolio
  branch: main
  base_url: https://decap-cms-oauth-provider.vercel.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "about"
    label: "عني"
    files:
      - file: "src/content/about.json"
        label: "معلومات عني"
        name: "about_info"
        fields:
          - { label: "الاسم", name: "name", widget: "string" }
          - { label: "المسمى الوظيفي", name: "title", widget: "string" }
          - { label: "النبذة التعريفية", name: "bio", widget: "text" }
